export { default as NotFound } from "./NotFound";
export { default as Home } from "./Home";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as StockSimulator } from "./StockSimulator";
export { default as StockScreenPage } from "./StockScreenPage";
export { default as WatchList } from "./WatchList";
export { default as Transaction } from "./Transaction";
export { default as Portfolio } from "./Portfolio";
